import type { SignalDrawerDto } from "@/lib/signals/types/signalDtos";
import { cn } from "@/lib/cn";

function IntegrityRow({ label, value, ok }: { label: string; value: string; ok?: boolean }) {
  return (
    <div className="flex items-center justify-between gap-2 py-1.5 border-b border-white/[0.04] last:border-0">
      <span className="text-[11px] text-[#70809A]">{label}</span>
      <span className={cn(
        "text-[11px] font-medium",
        ok === true ? "text-emerald-400" : ok === false ? "text-rose-400" : "text-[#A7B4C8]"
      )}>
        {value}
      </span>
    </div>
  );
}

function formatAge(ageSeconds: number): string {
  if (ageSeconds < 60) return `${ageSeconds}s ago`;
  if (ageSeconds < 3600) return `${Math.floor(ageSeconds / 60)}m ago`;
  return `${Math.floor(ageSeconds / 3600)}h ago`;
}

export function SignalIntegrityPanel({ signal }: { signal: SignalDrawerDto }) {
  const { freshness, status, market, confidenceScore, lockedFields } = signal;
  const isDelayed = freshness.isDelayed;
  const ageOk = freshness.ageSeconds < 3600;
  const lockedCount = lockedFields ? Object.values(lockedFields).filter(Boolean).length : 0;

  return (
    <div className="rounded-2xl border border-white/[0.06] bg-[#0B1728] p-4 md:p-5">
      <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-[0.1em] text-[#70809A]">Signal Integrity</h3>
      <p className="mb-3 text-[11px] text-[#4A5568]">Data freshness, source coverage, and publication policy.</p>

      <div>
        <IntegrityRow
          label="Data Freshness"
          value={ageOk ? formatAge(freshness.ageSeconds) : `${formatAge(freshness.ageSeconds)} — stale`}
          ok={ageOk}
        />
        <IntegrityRow
          label="Feed Type"
          value={isDelayed ? "Delayed (15-min)" : "Live / Near-live"}
          ok={!isDelayed}
        />
        <IntegrityRow
          label="Freshness Badge"
          value={freshness.badge}
          ok={freshness.badge === "FRESH"}
        />
        <IntegrityRow
          label="Market"
          value={market}
        />
        <IntegrityRow
          label="Signal Status"
          value={status}
          ok={status === "PUBLISHED" || status === "TRIGGERED"}
        />
        <IntegrityRow
          label="Confidence Score"
          value={`${confidenceScore}%`}
          ok={confidenceScore >= 70}
        />
        <IntegrityRow
          label="Premium-Locked Fields"
          value={lockedCount === 0 ? "None" : `${lockedCount} field${lockedCount !== 1 ? "s" : ""} locked`}
          ok={lockedCount === 0}
        />
      </div>

      <div className="mt-3 rounded-xl bg-white/[0.02] px-3 py-2">
        <p className="text-[10px] leading-relaxed text-[#4A5568]">
          Luffy signals are generated by an automated scanning engine and validated against multi-source market data.
          Signals are not financial advice. Always verify independently before trading.
        </p>
      </div>
    </div>
  );
}
