export const BACKOFF_BASE_DELAY_MS = 2_000;
export const BACKOFF_MAX_DELAY_MS = 30_000;
export const SOFT_FAILURE_THRESHOLD = 3;
export const HARD_FAILURE_THRESHOLD = 5;
export const FORCED_RESET_AFTER_MS = 120_000;
export const PROVIDER_HEALTHY_AGE_MS = 5_000;
export const PROVIDER_STALE_AFTER_MS = 15_000;
export const PROVIDER_PUBLICATION_MAX_AGE_MS = 120_000;

export const SNAPSHOT_SAFE_DISPLAY_TTL_MS = 120_000;
export const SNAPSHOT_SIGNAL_TTL_MS = 60_000;
export const SNAPSHOT_ENTRY_TTL_MS = 15_000;
export const SNAPSHOT_STRUCTURE_TTL_MS = 120_000;

export const LIVE_PRICE_CACHE_TTL_MS = 10_000;
export const SNAPSHOT_PRICE_CACHE_TTL_MS = 30_000;
export const CANDLE_CACHE_TTL_MS = 60_000;
export const STRUCTURE_CACHE_TTL_MS = 90_000;

export const RECOVERY_LOOP_INTERVAL_MS = 10_000;
export const SCANNER_SLOW_AFTER_MS = 6 * 60_000;
export const SCANNER_STALE_AFTER_MS = 10 * 60_000;
export const SCANNER_MIN_USABLE_COVERAGE_PCT = 5;
export const SCANNER_RECOVERY_CYCLES_REQUIRED = 2;
